language: java
jdk: oraclejdk8
dist: trusty
addons:
  sonarcloud:
    organization: "tesler-platform"
    token:
      secure: mhMWPBNskvGSVY6ecpe8w4IcwU7adEWCMe3wK8xQ7WSLWsLYNNsbIR6WOZqD0ikTcLuoEX0C56bAvdZW+f2jyFYcr7TaTUFv0u1TbX6OYlhlpLSa1mZIcI7HM/PFBGnKgJDywDZI2gZMUPv3pQUuV4ZMqofM3GHFux6lapHLrsOJxHzch1gO1nUJCmbcLmM439htU9pbGX29I//MSIjopwxuoGHCWT4DQB4DKv4kC8cSy1RWnQTWor5UXUPJuzHtlDH8efRwrP9xBuVZP5Io1Ye77HoUqoLKwe2IbaRH34HfZQPVajfflyzANKdqCPFID4CBoXISD90i9qbS4and0KqeVyeQo+NwWg13+Bb7UU2LBKCEqWqe/2zvKACPvv26Dk8HHlsjA5O1MyzIe7XbyqDlP7R4FGlWB8uLj5qQjwa4eN145C/VAxezvB4EajFJu/oL/OSzEL0dUm+OnBFWN3FuXvl/Gb7IdOYRC74+d4IgusvECTGyPdF9QNWaDFoG3MpWa7hHXLlpZG4JA7tD1s13wGhmaqjLlipu9g2rPTWGwNG7GxYBzRTc54pCR7o8xZ6xZOn1Rdk/9xhF5iNiv4fTlscXrOeIUxBiWMFQ8IaNG/UZIMJ4d0T+rLC06PPZ60pDGNhbqgpSCfrLwfAKvOK9SKRIHPtTduysc40gqcM=
script:
  - mvn clean install -Pcoverage sonar:sonar -Dsonar.projectKey=tesler-platform_tesler
after_success:
  - bash <(curl -s https://codecov.io/bash)
